#!/bin/bash

# This script must be run from the root of the dcs_nifi project
# This script requires that nifi be available at dcs-flow:8090
mkdir -p log
sbt flow/it:test > log/flowittest-`date +"%m%d%y"`.out
 
